package com.hootsuite.krrxd.dagger

import android.arch.persistence.room.Room
import android.content.Context
import com.hootsuite.krrxd.persistence.AppDatabase
import com.hootsuite.krrxd.persistence.UserDao
import dagger.Module
import dagger.Provides

@Module class AppModule(private val context: Context) {

    @Provides fun providesAppContext() = context

    /**
     * Build the room db with the application context, using some db name
     */
    @Provides fun providesAppDatabase(context: Context): AppDatabase =
            Room.databaseBuilder(context, AppDatabase::class.java, "login-db").build()

    /**
     * Provides the [UserDao] generated by the given [AppDatabase]
     */
    @Provides fun providesUserDao(database: AppDatabase) = database.userDao()
}